* configure.ac: Added test for broken <stdbool.h>. * tpoll.c: Removed <stdbool.h> include in favor of AC's "config.h".

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4452,6 +4452,62 @@ done
 
 
 
+{ echo "$as_me:$LINENO: checking whether stdbool.h is broken" >&5
+echo $ECHO_N "checking whether stdbool.h is broken... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <stdbool.h>
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+   broken_stdbool=no
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	 broken_stdbool=yes
+
+cat >>confdefs.h <<\_ACEOF
+#define BROKEN_STDBOOL 1
+_ACEOF
+
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: ${broken_stdbool=no}" >&5
+echo "${ECHO_T}${broken_stdbool=no}" >&6; }
+
+
+
+
 { echo "$as_me:$LINENO: checking whether debugging is enabled" >&5
 echo $ECHO_N "checking whether debugging is enabled... $ECHO_C" >&6; }
 # Check whether --enable-debug was given.
