* etc/conman.init: Revamped.

diff --git a/etc/conman.init b/etc/conman.init
--- a/etc/conman.init
+++ b/etc/conman.init
@@ -2,126 +2,322 @@
 ###############################################################################
 # $Id$
 ###############################################################################
-# chkconfig:	345 95 5
-# description:	The ConMan daemon is used for console management.
-# processname:	conmand
-# config:	/etc/conman.conf
+# chkconfig:      345 95 5
+###############################################################################
+### BEGIN INIT INFO
+# Provides:       conman
+# Required-Start: $named $network $time
+# Required-Stop:  $named $network $time
+# Should-Start:   $local_fs $syslog
+# Should-Stop:    $local_fs $syslog
+# Default-Start:  3 4 5
+# Default-Stop:   0 1 2 6
+# Description:    The ConMan daemon is used for serial console management.
+### END INIT INFO
 ###############################################################################
 
 SERVICE="ConMan"
-DAEMON="conmand"
+DAEMON="/usr/sbin/conmand"
+CONFIG="/etc/conman.conf"
+OPTIONS="-c $CONFIG"
 
-PATH=/usr/sbin:/usr/local/sbin:/bin:/usr/bin:/usr/local/bin
-which "$DAEMON" 1>/dev/null 2>&1 || exit 1
+PATH=/sbin:/usr/sbin:/usr/local/sbin:/bin:/usr/bin:/usr/local/bin
+
+[ -x "$DAEMON" ] || exit 5              # error: program is not installed
+[ -f "$CONFIG" ] || exit 6              # error: program is not configured
 
 ###############################################################################
 
-REDHAT_FUNCTIONS="/etc/rc.d/init.d/functions"
-REDHAT_SUBSYS="`echo $0 | perl -pe 's|(.*/)?([SK][0-9]{2})?(.*)|$3|'`"
-
-###############################################################################
-
-start_proc()
+service_init ()
 {
+# Determine the system type and initialize the environment.
+#
+# Note that the shell positional parameters must be preserved when calling
+#   this function in order for SuSE to initialize its environment properly.
+##
+  local RH_SUBSYS_BASENAME
+
+  rc=0
+  if test -f /etc/init.d/functions; then
+    SYSTEM="REDHAT"
+    source /etc/init.d/functions
+    RH_SUBSYS_BASENAME="`echo $0 | perl -pe 's,(.*/)?([SK][0-9]{2})?(.*),$3,'`"
+    RH_SUBSYS="/var/lock/subsys/$RH_SUBSYS_BASENAME"
+    INITLOG_ARGS=""                     # disable RH suppression of stderr msgs
+  elif test -f /etc/rc.status; then
+    SYSTEM="SUSE"
+    source /etc/rc.status
+    rc_reset
+  elif test -f /lib/lsb/init-functions; then
+    SYSTEM="LSB"
+    source /lib/lsb/init-functions
+  else
+    SYSTEM="UNKNOWN"
+  fi
+}
+
+###############################################################################
+
+service_fini ()
+{
+# Return the exit status.
+##
+  case "$SYSTEM" in
+    SUSE)
+      rc_exit
+      ;;
+    LSB|REDHAT|*)
+      exit $rc
+      ;;
+  esac
+}
+
+###############################################################################
+
+service_start ()
+{
+# Start the service.
+# Required by LSB.
+#
+# Running "start" on a service already running should be considered successful.
+##
   echo -n "Starting $SERVICE: "
-  if test -x "$REDHAT_FUNCTIONS"; then
-    source "$REDHAT_FUNCTIONS"
-    INITLOG_ARGS=""
-    daemon "$DAEMON"
-    RETVAL="$?"
-    test "$RETVAL" -eq 0 && touch "/var/lock/subsys/$REDHAT_SUBSYS" 2>/dev/null
-    echo
-  else
-    "$DAEMON" 2>/dev/null
-    RETVAL="$?"
-    test "$RETVAL" -eq 0 && echo success || echo failure
-  fi
+  case "$SYSTEM" in
+    LSB)
+      start_daemon "$DAEMON" $OPTIONS
+      rc=$?
+      [ $rc -eq 0 ] && log_success_msg || log_failure_msg
+      ;;
+    REDHAT)
+      daemon "$DAEMON" $OPTIONS
+      rc=$?
+      echo
+      [ $rc -eq 0 ] && touch "$RH_SUBSYS" 2>/dev/null
+      ;;
+    SUSE)
+      startproc "$DAEMON" $OPTIONS
+      rc_status -v
+      ;;
+    *)
+      "$DAEMON" $OPTIONS 2>/dev/null
+      rc=$?
+      [ $rc -eq 0 ] && echo success || echo failure
+      ;;
+  esac
 }
 
 ###############################################################################
 
-stop_proc()
+service_stop ()
 {
+# Stop the service.
+# Required by LSB.
+#
+# Running "stop" on a service already stopped or not running should be
+#   considered successful.
+##
   echo -n "Stopping $SERVICE: "
-  if test -x "$REDHAT_FUNCTIONS"; then
-    source "$REDHAT_FUNCTIONS"
-    INITLOG_ARGS=""
-    killproc "$DAEMON"
-    RETVAL="$?"
-    test "$RETVAL" -eq 0 && rm -f "/var/lock/subsys/$REDHAT_SUBSYS" 2>/dev/null
-    echo
-  else
-    "$DAEMON" -k 2>/dev/null
-    RETVAL="$?"
-    test "$RETVAL" -eq 0 && echo success || echo failure
-  fi
+  case "$SYSTEM" in
+    LSB)
+      killproc "$DAEMON"
+      rc=$?
+      [ $rc -eq 0 ] && log_success_msg || log_failure_msg
+      ;;
+    REDHAT)
+      killproc "$DAEMON"
+      rc=$?
+      echo
+      [ $rc -eq 0 ] && rm -f "$RH_SUBSYS" 2>/dev/null
+      ;;
+    SUSE)
+      killproc "$DAEMON"
+      rc_status -v
+      ;;
+    *)
+      "$DAEMON" $OPTIONS -k 2>/dev/null
+      rc=$?
+      [ $rc -eq 0 ] && echo success || echo failure
+      ;;
+  esac
 }
 
 ###############################################################################
 
-reload_proc()
+service_restart ()
 {
+# Stop and restart the service if it is already running;
+#   otherwise, start the service.
+# Required by LSB.
+#
+# Running "restart" on a service already stopped or not running should be
+#   considered successful.
+##
+  $0 status >/dev/null && $0 stop
+  $0 start
+
+  case "$SYSTEM" in
+    SUSE)
+      rc_status
+      ;;
+    LSB|REDHAT|*)
+      rc=$?
+      ;;
+  esac
+}
+
+###############################################################################
+
+service_try_restart ()
+{
+# Restart the service if it is already running.
+# Optional for LSB.  Also known as "condrestart" by RedHat.
+#
+# Running "try-restart" on a service already stopped or not running should be
+#   considered successful.
+##
+  case "$SYSTEM" in
+    REDHAT)
+      [ -f "$RH_SUBSYS" ] && $0 restart || :
+      rc=$?
+      ;;
+    SUSE)
+      $0 status >/dev/null && $0 restart || rc_reset
+      rc_status
+      ;;
+    LSB|*)
+      $0 status >/dev/null && $0 restart || :
+      rc=$?
+      ;;
+  esac
+}
+
+###############################################################################
+
+service_reload ()
+{
+# Reload the configuration without stopping and restarting the service.
+# Optional for LSB.
+##
+  rc=3                                  # error: unimplemented feature
   echo -n "Reloading $SERVICE: "
-  if test -x "$REDHAT_FUNCTIONS"; then
-    source "$REDHAT_FUNCTIONS"
-    INITLOG_ARGS=""
-    killproc "$DAEMON" -HUP
-    RETVAL="$?"
-    echo
-  else
-    "$DAEMON" -r 2>/dev/null
-    RETVAL="$?"
-    test "$RETVAL" -eq 0 && echo success || echo failure
-  fi
+  case "$SYSTEM" in
+    LSB)
+#     killproc "$DAEMON" -HUP
+#     rc=$?
+      [ $rc -eq 0 ] && log_success_msg || log_failure_msg
+      ;;
+    REDHAT)
+#     killproc "$DAEMON" -HUP
+#     rc=$?
+      echo_failure
+      echo
+      ;;
+    SUSE)
+#     killproc -HUP "$DAEMON"
+      rc_failed $rc
+      rc_status -v
+      ;;
+    *)
+#     "$DAEMON" $OPTIONS -r 2>/dev/null
+#     rc=$?
+      [ $rc -eq 0 ] && echo success || echo failure
+      ;;
+  esac
 }
 
 ###############################################################################
 
-check_proc()
+service_force_reload ()
 {
-  if test -x "$REDHAT_FUNCTIONS"; then
-    source "$REDHAT_FUNCTIONS"
-    INITLOG_ARGS=""
-    status "$DAEMON"
-    RETVAL="$?"
-  else
-    pid="`\"$DAEMON\" -q 2>/dev/null`"
-    if test -n "$pid"; then
-      echo "$DAEMON (pid $pid) is running..."
-      RETVAL="0"
-    else
-      echo "$DAEMON is stopped"
-      RETVAL="3"
-    fi
-  fi
+# Reload the configuration if the service supports this;
+#   otherwise, restart the service if it is already running.
+# Required by LSB.
+# 
+# Running "force-reload" on a service already stopped or not running should be
+#   considered successful.
+##
+  $0 try-restart
+
+  case "$SYSTEM" in
+    SUSE)
+      rc_status
+      ;;
+    LSB|REDHAT|*)
+      rc=$?
+      ;;
+  esac
 }
 
 ###############################################################################
 
-RETVAL="13"
+service_status ()
+{
+# Print the current status of the service.
+# Required by LSB.
+##
+  case "$SYSTEM" in
+    LSB)
+      pids=`pidofproc "$DAEMON" 2>/dev/null`
+      rc=$?
+      if [ $rc -eq 0 ]; then
+        echo "`basename $DAEMON` (pid $pids) is running..."
+      else
+        echo "`basename $DAEMON` is stopped"
+      fi
+      ;;
+    REDHAT)
+      status "$DAEMON"
+      rc=$?
+      ;;
+    SUSE)
+      echo -n "Checking for $SERVICE: "
+      checkproc "$DAEMON"
+      rc_status -v
+      ;;
+    *)
+      pids=`"$DAEMON" $OPTIONS -q 2>/dev/null`
+      rc=$?
+      if [ $rc -eq 0 -a -n "$pids" ]; then
+        echo "`basename $DAEMON` (pid $pids) is running..."
+      else
+        echo "`basename $DAEMON` is stopped"
+        rc=3
+      fi
+      ;;
+  esac
+}
+
+###############################################################################
+
+service_init "$@"
 
 case "$1" in
   start)
-    ulimit -n 8192 2>/dev/null          # tmp kludge for large fd support
-    start_proc
+    service_start
     ;;
   stop)
-    stop_proc
+    service_stop
     ;;
   restart)
-    stop_proc
-    ulimit -n 8192 2>/dev/null          # tmp kludge for large fd support
-    start_proc
+    service_restart
     ;;
-  reload|force-reload)
-    reload_proc
+  try-restart|condrestart)
+    service_try_restart
+    ;;
+  reload)
+    service_reload
+    ;;
+  force-reload)
+    service_force_reload
     ;;
   status)
-    check_proc
+    service_status
     ;;
   *)
-    echo "Usage: $DAEMON {start|stop|restart|reload|force-reload|status}"
-    exit 1
+    COMMANDS="start|stop|restart|try-restart|reload|force-reload|status"
+    echo "Usage: `basename $0` ($COMMANDS)"
+    exit 2                              # error: invalid or excess argument(s)
+    ;;
 esac
 
-exit $RETVAL
+service_fini
